import { ColDef } from "ag-grid-community";

export const defaultColumns: ColDef[] = [
  {
    headerName: "",
    field: "on",
    width: 70,
    flex: 1,
    checkboxSelection: true,
    headerCheckboxSelection: true,
    pinned: "left",
    suppressHeaderMenuButton: true,
    suppressHeaderFilterButton: true,
    resizable: false,
    suppressColumnsToolPanel: true,
    filter: false,
    sortable: false,
  },
  {
    headerName: "Transaction ID",
    field: "transaction_id",
    filter: "agTextColumnFilter",
    sortable: true,
    editable: false,
  },
  {
    headerName: "Date",
    field: "date",
    filter: "agDateColumnFilter",
    sortable: true,
    editable: true,
  },
  {
    headerName: "Customer ID",
    field: "customer_id",
    filter: "agTextColumnFilter",
    sortable: true,
    editable: false,
  },
  {
    headerName: "Amount",
    field: "amount",
    filter: "agNumberColumnFilter",
    sortable: true,
    editable: true,
    cellClass: ["numeric-cell", "editable-cell"],
  },
  {
    headerName: "Type",
    field: "type",
    filter: "agTextColumnFilter",
    sortable: true,
    editable: false,
  },
  {
    headerName: "Description",
    field: "description",
    filter: "agTextColumnFilter",
    sortable: true,
    editable: false,
  },
];
